var footerTag;
footerTag ='<div id="footer" class="spFt" role="contentinfo">'
+'			<div class="foot_section">'
+'				<div class="foot_opt_area">'
+'					<ul class="foot_opt_list">'
+'						<li><a href="#" target="_blank" title="새창">개인정보취급방침</a></li>'
+'						<li><a href="#" target="_blank" title="새창"><em>영상정보처리기기운영, 관리방침</em></a></li>'
+'						<li><a href="#" target="_blank" title="새창">약관안내</a></li>'
+'						<li><a href="#" target="_blank" title="새창">윤리경영</a></li>'
+'						<li><a href="#" target="_blank" title="새창">전자세금 계산서</a></li>'
+'						<li><a href="#">공지사항</a></li>'
+'						<li><a href="#" target="_blank" title="새창">대량구매/협업문의</a></li>'
+'					</ul>'
+'				</div>'
+'				<div class="cont">'
+'					<div>'
+'						<h3><a href="#"><em class="ir">SHOOPEN</em></a></h3>'
+'						<div class="info">'
+'							<dl class="tx">'
+'								<dt>(주)이랜드리테일</dt>'
+'								<dd>대표이사: 김우석, 석창현   주소: 서울특별시 서초구 잠원동 70번지 2호</dd>'
+'								<dd>사업자등록번호: 114-81-01855 <button type="button"><em>사업자 정보확인</em></button>통신판매업 신고번호: 제 2007-서울서초-09998호   </dd>'
+'								<dd>개인정보보호 책임자: 이동규<span class="mail">Email: <a href="mailto:webmaster@elandmall.com">webmaster@elandmall.com</a></span></dd>'
+'								<dd>Copyright © Eland Retail. All Rights Reserved. </dd>'
+'							</dl>'
+'							<div class="app">'
+'								<img src="../../images/pcweb/sp_pcweb/common/ico_qr.jpg" alt="스마트폰 QR코드스캔 시 슈펜 APP 다운로드 이동" />'
+'								<b>슈펜 APP 다운로드</b>'
+'								<em>스마트폰으로 QR코드 스캔</em>'
+'							</div>'
+'						</div>'
+'						<div class="foot_side_opt">'
+'							<div class="fm_links">'
+'								<a class="btn_fm_site" href="#"><span>패밀리 사이트 바로가기</span></a>'
+'								<div class="list_fm_site">'
+'									<ul class="scroll">'
+'										<li><a href="#">이랜드 리테일</a></li>'
+'										<li><a href="#">모던하우스</a></li>'
+'										<li><a href="#">이랜드 그룹</a></li>'
+'										<li><a href="#">MIXXO</a></li>'
+'										<li><a href="#">SPAO</a></li>'
+'										<li><a href="#">패밀리 사이트 패밀리 사이트</a></li>'
+'									</ul>'
+'								</div>'
+'							</div>'
+'							<div class="foot_cs">'
+'								<strong class="foot_csph">1899-9500</strong>'
+'								<span class="foot_cstxt">상담시간 : 오전9시~오후6시 (토요일, 공휴일은 쉽니다) </span>'
+'								<button type="button" class="auth_btn">협력사 입직원 인증</button>'
+'								<button type="button" class="auth_btn">임직원 회원가입 / 인증</button>'
+'							</div>'
+'						</div>'
+'					</div>'
+'				</div>'
+'				<div class="foot_bot">'
+'					<div>'
+'						<p><strong>소비자피해보상보험</strong> 고객님은 안전거래를 위해 현금 등으로 결제시 저희 쇼핑몰에서 가입한 구매 안전서비스를 이용하실 수 있습니다.</p>'
+'						<button type="button" class="btn07 c01 ico_arrow04"><span>서비스 가입사실 확인하기</span></button>'
+'						<ul class="foot_menus"> <!-- 2018.07.12 변경 : isms_info, norton 클래스 삽입 유의 -->'
+'							<li class="isms_info">'
+'								<a href="#" target="_blank" title="새창"><img src="../../images/pcweb/common/foot_menu04.png" alt="정보관리체계인증(ISMS) 마크">'
+'									<span>'
+'										정보보호관리체계 ISMS 인증 획득<br />	고객님의 소중한 정보는 안전하게 관리되고 있습니다.<br />유효기간 : 2017.11.27 ~ 2020.11.26'
+'									</span>'
+'								</a>'
+'							</li>'
+'							<li class="norton"><a href="#" target="_blank" title="새창"><img src="../../images/pcweb/common/foot_menu03.png" alt="Norton Secured"></a></li>'
+'						</ul>'
+'					</div>'
+'				</div>'
+'			</div>'
+'		</div>'
+'		<div class="fxdTop"><a href="#none" aria-label="최상단으로 이동"><em>TOP</em></a></div>'
document.write(footerTag);
