var headerTag;
headerTag ='<div class="header_top_banner on" style="background-color:#d9dedd;">'
+'			<div class="btn_hdtb_img"><a href="#"><img src="../../images/pcweb/temp/_temp_1080x80_shoopen.jpg" alt="하나 사고 하나 더 받고!" /></a></div>'
+'			<a href="#" class="btn_hdtb_close">베너 닫기</a>'
+'		</div>'
+'		<div id="header" class="header" role="banner">'
+'			<div class="head">'
+'				<h1><a href="#"><strong class="ir">SHOOPEN</strong></a></h1>'
+'				<ul class="logBx">'
+'					<li><a href="#">로그인<em class="ir">레이어 열기</em></a></li>'
+'					<li><a href="#">회원가입</a></li>'
+'				</ul>'
+'				<div class="hd_disp">'
+'					<dl>'
+'						<dt class="ir">카테고리메뉴</dt>'
+'						<dd><div><a href="#" class="bt">슈탠다드</a></div></dd>'
+'						<dd><div><a href="#" class="bt">콜라보레이션</a></div></dd>'
+'						<dd>'
+'							<div role="combobox" aria-owns="hd_disp_0" aria-expanded="false">'
+'								<a href="#" class="bt" aria-controls="hd_disp_0">WOMEN</a><!-- 해당 페이지 진입시 aria-current="page" 추가 -->'
+'								<div class="depth2" id="hd_disp_0">'
+'									<div>'
+'										<dl class="ctg">'
+'											<dt><a href="#">여성홈</a></dt>'
+'											<dd><a href="#">신상모아보기</a></dd>'
+'											<dd><a href="#">베스트 셀러</a></dd>'
+'											<dd><a href="#">스페셜 딜</a></dd>'
+'										</dl>'
+'										<dl class="ctg">'
+'											<dt><a href="#">여성신발</a></dt>'
+'											<dd><a href="#">운동화</a></dd>'
+'											<dd><a href="#">플랫/단화</a></dd>'
+'											<dd><a href="#">로퍼/블로퍼</a></dd>'
+'											<dd><a href="#">펌프스/힐</a></dd>'
+'											<dd><a href="#">샌들/슬리퍼</a></dd>'
+'											<dd><a href="#">부츠/워커</a></dd>'
+'										</dl>'
+'										<dl class="ctg">'
+'											<dt><a href="#">여성가방</a></dt>'
+'											<dd><a href="#">숄더/토트백</a></dd>'
+'											<dd><a href="#">에코백/북백</a></dd>'
+'											<dd><a href="#">크로스백</a></dd>'
+'											<dd><a href="#">미니백</a></dd>'
+'											<dd><a href="#">파우치</a></dd>'
+'											<dd><a href="#">백팩</a></dd>'
+'											<dd><a href="#">기타</a></dd>'
+'										</dl>'
+'										<dl class="ctg">'
+'											<dt><a href="#">여성잡화</a></dt>'
+'											<dd><a href="#">양말</a></dd>'
+'											<dd><a href="#">모자</a></dd>'
+'											<dd><a href="#">머플러/장갑</a></dd>'
+'											<dd><a href="#">기타</a></dd>'
+'										</dl>'
+'										<dl class="bnr">'
+'											<dt class="ir">배너영역</dt>'
+'											<dd>'
+'												<a href="#">'
+'													<span class="img"><img src="../../images/pcweb/sp_pcweb/temp/bn_224x224_0.jpg" alt="" /></span>'
+'													<span class="tx">'
+'														<strong>슈펜X유미의세포들</strong>'
+'														<em>웹툰에서 튀어나온듯 완벽 재현</em>'
+'													</span>'
+'												</a>'
+'											</dd>'
+'											<dd>'
+'												<a href="#">'
+'													<span class="img"><img src="../../images/pcweb/sp_pcweb/temp/bn_224x224_1.jpg" alt="" /></span>'
+'													<span class="tx">'
+'														<strong>슈펜X유미의세포들</strong>'
+'														<em>웹툰에서 튀어나온듯 완벽 재현한 아이템들</em>'
+'													</span>'
+'												</a>'
+'											</dd>'
+'										</dl>'
+'									</div>'
+'								</div>'
+'							</div>'
+'						</dd>'
+'						<dd>'
+'							<div role="combobox" aria-owns="hd_disp_1" aria-expanded="false">'
+'								<a href="#" class="bt"  aria-controls="hd_disp_1">MEN</a>'
+'								<div class="depth2" id="hd_disp_1">'
+'									<div>'
+'										<dl class="ctg">'
+'											<dt><a href="#">남성홈</a></dt>'
+'											<dd><a href="#">신상모아보기</a></dd>'
+'											<dd><a href="#">베스트 셀러</a></dd>'
+'											<dd><a href="#">스페셜 딜</a></dd>'
+'										</dl>'
+'										<dl class="ctg">'
+'											<dt><a href="#">남성신발</a></dt>'
+'											<dd><a href="#">운동화운동화운동화운동화운동화운동화운동화</a></dd>'
+'											<dd><a href="#">정장화</a></dd>'
+'											<dd><a href="#">로퍼/블로퍼</a></dd>'
+'											<dd><a href="#">보트/슬립온</a></dd>'
+'											<dd><a href="#">샌들/슬리퍼</a></dd>'
+'											<dd><a href="#">부츠/워커</a></dd>'
+'										</dl>'
+'										<dl class="ctg">'
+'											<dt><a href="#">남성가방</a></dt>'
+'											<dd><a href="#">백팩</a></dd>'
+'											<dd><a href="#">메신저/크로스백</a></dd>'
+'											<dd><a href="#">숄더/토트백</a></dd>'
+'											<dd><a href="#">랩탑/브리프케이스</a></dd>'
+'											<dd><a href="#">클러치</a></dd>'
+'											<dd><a href="#">기타</a></dd>'
+'										</dl>'
+'										<dl class="ctg">'
+'											<dt><a href="#">남성잡화</a></dt>'
+'											<dd><a href="#">양말</a></dd>'
+'											<dd><a href="#">모자</a></dd>'
+'											<dd><a href="#">머플러/장갑</a></dd>'
+'											<dd><a href="#">기타</a></dd>'
+'										</dl>'
+'										<dl class="bnr">'
+'											<dt class="ir">배너영역</dt>'
+'											<dd>'
+'												<a href="#">'
+'													<span class="img"><img src="../../images/pcweb/sp_pcweb/temp/bn_224x224_4.jpg" alt="" /></span>'
+'													<span class="tx">'
+'														<strong>슈펜X유미의세포들</strong>'
+'														<em>웹툰에서 튀어나온듯 완벽 재현</em>'
+'													</span>'
+'												</a>'
+'											</dd>'
+'											<dd>'
+'												<a href="#">'
+'													<span class="img"><img src="../../images/pcweb/sp_pcweb/temp/bn_224x224_5.jpg" alt="" /></span>'
+'													<span class="tx">'
+'														<strong>슈펜X유미의세포들</strong>'
+'														<em>웹툰에서 튀어나온듯 완벽 재현한 아이템들</em>'
+'													</span>'
+'												</a>'
+'											</dd>'
+'										</dl>'
+'									</div>'
+'								</div>'
+'							</div>'
+'						</dd>'
+'						<dd>'
+'							<div role="combobox" aria-owns="hd_disp_2" aria-expanded="false">'
+'								<a href="#" class="bt" aria-controls="hd_disp_2">KIDS</a>'
+'								<div class="depth2" id="hd_disp_2">'
+'									<div>'
+'										<dl class="ctg">'
+'											<dt><a href="#">아동홈</a></dt>'
+'											<dd><a href="#">신상모아보기</a></dd>'
+'											<dd><a href="#">베스트 셀러</a></dd>'
+'											<dd><a href="#">스페셜 딜</a></dd>'
+'										</dl>'
+'										<dl class="ctg">'
+'											<dt><a href="#">아동신발</a></dt>'
+'											<dd><a href="#">운동화</a></dd>'
+'											<dd><a href="#">구두</a></dd>'
+'											<dd><a href="#">샌들/슬리퍼</a></dd>'
+'											<dd><a href="#">부츠/워커</a></dd>'
+'										</dl>'
+'										<dl class="ctg">'
+'											<dt><a href="#">아동가방</a></dt>'
+'											<dd><a href="#">실내화주머니</a></dd>'
+'											<dd><a href="#">책가방</a></dd>'
+'											<dd><a href="#">패션가방</a></dd>'
+'										</dl>'
+'										<dl class="ctg">'
+'											<dt><a href="#">아동잡화</a></dt>'
+'											<dd><a href="#">양말</a></dd>'
+'											<dd><a href="#">모자</a></dd>'
+'											<dd><a href="#">머플러/장갑</a></dd>'
+'											<dd><a href="#">기타</a></dd>'
+'										</dl>'
+'										<dl class="bnr">'
+'											<dt class="ir">배너영역</dt>'
+'											<dd>'
+'												<a href="#">'
+'													<span class="img"><img src="../../images/pcweb/sp_pcweb/temp/bn_224x224_2.jpg" alt="" /></span>'
+'													<span class="tx">'
+'														<strong>슈펜X유미의세포들</strong>'
+'														<em>웹툰에서 튀어나온듯 완벽 재현</em>'
+'													</span>'
+'												</a>'
+'											</dd>'
+'											<dd>'
+'												<a href="#">'
+'													<span class="img"><img src="../../images/pcweb/sp_pcweb/temp/bn_224x224_3.jpg" alt="" /></span>'
+'													<span class="tx">'
+'														<strong>슈펜X유미의세포들</strong>'
+'														<em>웹툰에서 튀어나온듯 완벽 재현한 아이템들</em>'
+'													</span>'
+'												</a>'
+'											</dd>'
+'										</dl>'
+'									</div>'
+'								</div>'
+'							</div>'
+'						</dd>'
+'					</dl>'
+'					<dl>'
+'						<dt class="ir">전시메뉴</dt>'
+'						<dd><div><a href="#" class="bt">랭킹</a></div></dd>'
+'						<dd><div><a href="#" class="bt">기획전</a></div></dd>'
+'						<dd><div><a href="#" class="bt">룩북</a></div></dd>'
+'						<dd><div><a href="#" class="bt">매거진</a></div></dd>'
+'						<dd><div><a href="#" class="bt">이벤트</a></div></dd>'
+'					</dl>'
+'				</div>'
+'				<div class="hd_my">'
+'					<ul>'
+'						<li>'
+'							<div class="schBx" role="combobox" aria-owns="hd_lyrSch" aria-expanded="false">'
+'								<a href="#" class="bt sch" aria-controls="hd_lyrSch"><em class="ir">검색레이어 열기</em></a>'
+'								<div class="hd_lyrSch" id="hd_lyrSch">'
+'									<h4 class="ir">검색레이어</h4>'
+'									<div class="top">'
+'										<label for="hd_search">오늘도 우산 꼭 챙겨요!<em class="ir">검색어입력</em></label>'
+'										<input id="hd_search" type="text">'
+'										<button type="button" class="bt_del" aria-label="검색어삭제"></button>'
+'										<button type="button" class="bt_sch" aria-label="검색하기"></button>'
+'									</div>'
+'									<div class="key">'
+'										<dl class="rct">'
+'											<dt>최근 검색어</dt>'
+'											<dd>'
+'												<ul>'
+'													<li><a href="#">스웨터</a><button type="button" class="del" aria-label="삭제"></button></li>'
+'													<li><a href="#">런닝화</a><button type="button" class="del" aria-label="삭제"></button></li>'
+'													<li><a href="#">스탠다드 뮬</a><button type="button" class="del" aria-label="삭제"></button></li>'
+'													<li><a href="#">#예쁘니까_청춘이다</a><button type="button" class="del" aria-label="삭제"></button></li>'
+'													<li><a href="#">#데이트룩</a><button type="button" class="del" aria-label="삭제"></button></li>'
+'													<li><a href="#">일꼬르소</a><button type="button" class="del" aria-label="삭제"></button></li>'
+'													<li><a href="#">구찌</a><button type="button" class="del" aria-label="삭제"></button></li>'
+'													<li><a href="#">필플랍</a><button type="button" class="del" aria-label="삭제"></button></li>'
+'													<li><a href="#">필플랍샌들</a><button type="button" class="del" aria-label="삭제"></button></li>'
+'													<li><a href="#">판도라반지</a><button type="button" class="del" aria-label="삭제"></button></li>'
+'												</ul>'
+'											</dd>'
+'											<dd class="btm"><button type="button" class="delAll">전체삭제</button></dd>'
+'										</dl>'
+'										<dl class="hot">'
+'											<dt>인기 검색어</dt>'
+'											<dd>'
+'												<ul>'
+'													<li><a href="#"><em>1</em>슬리퍼<span class="up" role="status" aria-label="순위상승"></span></a></li>'
+'													<li><a href="#"><em>2</em>TPBT19W08<span class="new" role="status" aria-label="순위신규진입">NEW</span></a></li>'
+'													<li><a href="#"><em>3</em>슬립온<span class="up" role="status" aria-label="순위상승"></span></a></li>'
+'													<li><a href="#"><em>4</em>실내화<span class="no" role="status" aria-label="순위변동없음"></span></a></li>'
+'													<li><a href="#"><em>5</em>운동화<span class="new" role="status" aria-label="순위신규진입">NEW</span></a></li>'
+'													<li><a href="#"><em>6</em>룸슈즈<span class="no" role="status" aria-label="순위변동없음"></span></a></li>'
+'													<li><a href="#"><em>7</em>양말<span class="up" role="status" aria-label="순위상승"></span></a></li>'
+'													<li><a href="#"><em>8</em>스니커즈<span class="down" role="status" aria-label="순위하락"></span></a></li>'
+'													<li><a href="#"><em>9</em>백팩<span class="no" role="status" aria-label="순위변동없음"></span></a></li>'
+'													<li><a href="#"><em>10</em>로우<span class="up" role="status" aria-label="순위상승"></span></a></li>'
+'												</ul>'
+'											</dd>'
+'										</dl>'
+'									</div>'
+'									<div class="auto">'
+'										<dl class="ctg">'
+'											<dt class="ir">카테고리</dt>'
+'											<dd><a href="#">신발<em>GO</em></a></dd>'
+'											<dd><a href="#">바지<em>GO</em></a></dd>'
+'										</dl>'
+'										<dl class="let">'
+'											<dt class="ir">추천검색어</dt>'
+'											<dd><a href="#"><em>구두</em></a></dd>'
+'											<dd><a href="#">아동<em>구두</em></a></dd>'
+'											<dd><a href="#">여아<em>구두</em></a></dd>'
+'											<dd><a href="#">치크<em>구두</em></a></dd>'
+'											<dd><a href="#">남성<em>구두</em></a></dd>'
+'											<dd><a href="#"><em>구두</em>로엠</a></dd>'
+'											<dd><a href="#"><em>구두</em>바비</a></dd>'
+'											<dd><a href="#">여자<em>구두</em></a></dd>'
+'										</dl>'
+'										<div class="none">입력하신 단어가 들어가 있는 추천어가 없습니다.</div>'
+'										<dl class="pln">'
+'											<dt>추천기획전</dt>'
+'											<dd>'
+'												<a href="#">'
+'													<span class="img"><img src="../../images/pcweb/sp_pcweb/temp/bn_132x132_0.jpg" alt="" /></span>'
+'													<span class="tx">[슈펜] 여성 삭스부츠 기획전</span>'
+'												</a>'
+'											</dd>'
+'											<dd>'
+'												<a href="#">'
+'													<span class="img"><img src="../../images/pcweb/sp_pcweb/temp/bn_132x132_1.jpg" alt="" /></span>'
+'													<span class="tx">[슈펜] 웹툰에서 튀어나온듯 완벽 재현한 아이템들 기획전</span>'
+'												</a>'
+'											</dd>'
+'											<dd>'
+'												<a href="#">'
+'													<span class="img"><img src="../../images/pcweb/sp_pcweb/temp/bn_132x132_2.jpg" alt="" /></span>'
+'													<span class="tx">[슈펜] 슈펜X유미의세포들 기획전</span>'
+'												</a>'
+'											</dd>'
+'											<dd class="more"><a href="#"><em class="ir">추천기획전</em>더보기</a></dd>'
+'										</dl>'
+'									</div>'
+'									<div class="cls"><button type="button">닫기<em class="ir">검색레이어 닫기</em></button></div>'
+'								</div>'
+'							</div>'
+'						</li>'
+'						<li><a href="#" class="bt crt"><em class="ir">장바구니 이동</em><strong><em class="ir">장바구니에 담긴상품</em>3</strong></a></li>'
+'						<li><a href="#" class="bt wsh"><em class="ir">찜목록 이동</em><strong><em class="ir">찜상품에 담긴상품</em>99</strong></a></li>'
+'						<li>'
+'							<div role="combobox" aria-owns="hd_lyrMy" aria-expanded="false">'
+'								<a href="#" class="bt my" aria-controls="hd_lyrMy"><em class="ir">마이메뉴 레이어 열기</em></a>'
+'								<div class="hd_lyrMy" id="hd_lyrMy">'
+'									<ul>'
+'										<li><a href="#">주문배송조회</a></li>'
+'										<li><a href="#">내리뷰</a></li>'
+'										<li><a href="#">내댓글</a></li>'
+'										<li><a href="#">이벤트 응모내역</a></li>'
+'									</ul>'
+'									<ul>'
+'										<li><a href="#">채팅상담</a></li>'
+'										<li><a href="#">브랜드 공지사항</a></li>'
+'										<li><a href="#">고객센터</a></li>'
+'									</ul>'
+'								</div>'
+'							</div>'
+'						</li>'
+'					</ul>'
+'				</div>'
+'			</div>'
+'		</div>'
document.write(headerTag);
