var headerTag;
headerTag ='<div class="header_top_banner on" style="background-color:#004C34;">'
+'            <div class="btn_hdtb_img">'
+'              <ul>'
+'                <li><a href="javascript:"><img src="../../images/pcweb/kms_pcweb/temp/img_1280x42.jpg" alt="" /></a></li>'
+'              </ul>'
+'            </div>'
+'            <a href="#" class="btn_hdtb_close">배너 닫기</a>'
+'            <a href="#" class="btn_hdtb_open"><span class="ir">배너 열기</span>OPEN</a>'
+'          </div>'      
+'          <div class="header wide"><!-- 기본 1080px / 메인 1200px 클래스명 wide 중첩 /  -->'
+'            <div class="header_top">'
+'              <ul class="q_txt login_bf">'
+'                <li><a href="#">로그인</a></li>'
+'                <li><a href="#">회원가입</a></li>'
+'                <li><a href="#">마이페이지</a></li>'
+'                <li><a href="#">고객센터</a></li>'
+'              </ul>'
+'              <ul class="q_txt login_at">'
+'                <li><a href="#">로그아웃</a></li>'
+'                <li><a href="#">마이페이지</a></li>'
+'                <li><a href="#">고객센터</a></li>'
+'              </ul>'
+'            </div>'
+'            <div class="header_mid">'
+'              <h1 class="logo"><a href="#"><strong class="ir">KIMS</strong></a></h1>'
+'              <div class="hd_sch" id="hd_sch" style="">'
+'                <div class="sch_wrap">'
+'                  <div class="sch_box">'
+'                    <label class="ir" for="searchTerm">검색</label>'
+'                    <input type="text" class="input d_searchTerm" name="sch" id="searchTerm" placeholder="검색어를 입력하세요." />'
+'                  </div>'
+'                  <div id="sch_keyword" class="sch_keyword d_sch_keyword">'
+'                    <dl class="f_keyword">'
+'                      <dt><button type="button" id="headerResentKwd_btn">최근 검색어</button></dt>'
+'                      <dd id="headerResentKwd">'
+'                        <ul class="recent_wrap hd_recent_kwd_area">'
+'                          <li><a href="javascript:;" class="d_links"><span>키보드키보드키보드키보드키보드키보드키보드</span></a><button type="button" class="del">삭제</button></li>'
+'                          <li><a href="javascript:;" class="d_links"><span>인테리어</span></a><button type="button" class="del">삭제</button></li>'
+'                          <li><a href="javascript:;" class="d_links"><span>키보드</span></a><button type="button" class="del">삭제</button></li>'
+'                          <li><a href="javascript:;" class="d_links"><span>인테리어</span></a><button type="button" class="del">삭제</button></li>'
+'                          <li><a href="javascript:;" class="d_links"><span>키보드</span></a><button type="button" class="del">삭제</button></li>'
+'                          <li><a href="javascript:;" class="d_links"><span>인테리어</span></a><button type="button" class="del">삭제</button></li>'
+'                          <li><a href="javascript:;" class="d_links"><span>키보드</span></a><button type="button" class="del">삭제</button></li>'
+'                          <li><a href="javascript:;" class="d_links"><span>인테리어</span></a><button type="button" class="del">삭제</button></li>'
+'                        </ul>'
+'                        <div class="s_del hd_recent_kwd_area"><button type="button">최근 검색어 전체 삭제</button></div>'
+'                        <!-- <div class="msg">최근 검색어 내역이 없습니다.</div> -->'
+'                        <div class="k_recent" id="k_recent">'
+'                          <strong class="tit">최근 본 상품</strong>'
+'                          <ul>'
+'                            <li><a href="javascript:;"><img src="../../images/pcweb/temp/_sample_115x115_01.png" alt="" /></a><button type="button" id="" class=""><em class="ir">삭제</em></button></li>'
+'                            <li><a href="javascript:;"><img src="../../images/pcweb/temp/_sample_115x115_01.png" alt="" /></a><button type="button" id="" class=""><em class="ir">삭제</em></button></li>'
+'                            <li><a href="javascript:;"><img src="../../images/pcweb/temp/_sample_115x115_01.png" alt="" /></a><button type="button" id="" class=""><em class="ir">삭제</em></button></li>'
+'                            <li><a href="javascript:;"><img src="../../images/pcweb/temp/_sample_115x115_01.png" alt="" /></a><button type="button" id="" class=""><em class="ir">삭제</em></button></li>'
+'                          </ul>'
+'                          <div class="all_view">'
+'                            <a href="javascript:;">전체보기</a>'
+'                          </div>'
+'                          <!-- <div class="msg">최근 본 상품 내역이 없습니다.</div> -->'
+'                        </div>'
+'                      </dd>'
+'                      <dt><button type="button" id="rankings_btn" class="on">인기 검색어</button></dt>'
+'                      <dd id="rankings_dd">'
+'                        <ol class="hot_keyword" id="rankings">'
+'                          <li class="rank">'
+'                            <a href="javascript:;" class="d_links top"><em class="num">1</em><span>아이폰 6S</span></a>'
+'                            <div class="rl_pot"><span class="rl_up">213</span></div>'
+'                          </li>'
+'                          <li class="rank">'
+'                            <a href="javascript:;" class="d_links top"><em class="num">1</em><span>모던하우스</span></a>'
+'                            <div class="rl_pot"><span class="rl_down">32</span></div>'
+'                          </li>'
+'                          <li class="rank">'
+'                            <a href="javascript:;" class="d_links top"><em class="num">3</em><span>패딩</span></a>'
+'                            <div class="rl_pot"><span class="rl_up">24</span></div>'
+'                          </li>'
+'                          <li class="rank">'
+'                            <a href="javascript:;" class="d_links"><em class="num">4</em><span>겨울잠바</span></a>'
+'                            <div class="rl_pot">-</div>'
+'                          </li>'
+'                          <li class="rank">'
+'                            <a href="javascript:;" class="d_links"><em class="num">5</em><span>스파오</span></a>'
+'                            <div class="rl_pot"><span class="point">NEW</span></div> <!-- span.point 추가  -->'
+'                          </li>'
+'                          <li class="rank">'
+'                            <a href="javascript:;" class="d_links"><em class="num">6</em><span>여성 영클부츠</span></a>'
+'                            <div class="rl_pot"><span class="rl_up">24</span></div>'
+'                          </li>'
+'                          <li class="rank">'
+'                            <a href="javascript:;" class="d_links"><em class="num">1</em><span>아이폰 6S</span></a>'
+'                            <div class="rl_pot"><span class="rl_up">213</span></div>'
+'                          </li>'
+'                          <li class="rank">'
+'                            <a href="javascript:;" class="d_links"><em class="num">1</em><span>모던하우스</span></a>'
+'                            <div class="rl_pot"><span class="rl_down">32</span></div>'
+'                          </li>'
+'                          <li class="rank">'
+'                            <a href="javascript:;" class="d_links"><em class="num">3</em><span>패딩</span></a>'
+'                            <div class="rl_pot"><span class="rl_up">24</span></div>'
+'                          </li>'
+'                          <li class="rank">'
+'                            <a href="javascript:;" class="d_links"><em class="num">4</em><span>겨울잠바</span></a>'
+'                            <div class="rl_pot">-</div>'
+'                          </li>'
+'                        </ol>'
+'                      </dd>'
+'                     </dl>'
+'                     <div class="cls"><button type="button">닫기<em class="ir">검색레이어 닫기</em></button></div>'
+'                   </div>'
+'                   <div id="sch_complete" class="sch_keyword d_sch_complete">'
+'                     <div class="s_keyword">'
+'                       <ul class="sch_ing">'
+'                         <li><a href="#" class="d_links"><span>청청청청청청청청청청청청청청청청청청청청청<b>바지</b><em>09.20</em></span></a></li>'
+'                         <li><a href="#" class="d_links"><span>디젤청<b>바지</b><em>09.20</em></span></a></li>'
+'                         <li><a href="#" class="d_links"><span>등산<b>바지</b><em>09.20</em></span></a></li>'
+'                         <li><a href="#" class="d_links"><span><b>바지</b>걸이</span></a></li>'
+'                         <li><a href="#" class="d_links"><span>트레이닝<b>바지</b></span></a></li>'
+'                         <li><a href="#" class="d_links"><span><b>바지</b></span></a></li>'
+'                         <li><a href="#" class="d_links"><span>등산<b>바지</b><em>09.20</em></span></a></li>'
+'                         <li><a href="#" class="d_links"><span><b>바지</b>걸이</span></a></li>'
+'                         <li><a href="#" class="d_links"><span>트레이닝<b>바지</b></span></a></li>'
+'                         <li><a href="#" class="d_links"><span><b>바지</b></span></a></li>'
+'                       </ul>'
+'                       <!-- <div class="msg">입력하신 단어가 들어가 있는 추천어가 없습니다.</div> -->'
+'                     </div>'
+'                     <div class="delL"><button type="button">닫기</button></div>'
+'                   </div>'
+'                   <button type="button" id="sch_del" class="sch_del" title="삭제하기">삭제</button>'
+'                   <button type="button" id="sch_btn" class="sch_btn" title="검색하기">검색</button>'
+'                 </div>'
+'               </div>'
+'               <ul class="q_icon">'
+'                 <li><a href="#" class="wish"><em class="ir">위시리스트 이동</em></a></li>'
+'                 <li><a href="#" class="deliv"><em class="ir">배송조회 이동</em><span class="num">99</span></a></li>'
+'                 <li><a href="#" class="cart"><em class="ir">장바구니 이동</em><span class="num">99</span></a></li>'
+'               </ul>'
+'             </div>'
+'             <div class="header_bot">'
+'               <ul class="gnb catg_wrap">'
+'                 <button type="button" id="catg_bt" class="all catg_bt">전체 카테고리</button>'
+'                   <div class="catg_lyr" id="catg_lyr">'
+'                     <div class="cate_all">'
+'                       <div id="" class="lnb_cate_main">'
+'                         <ul>'
+'                           <li class="depth_division">FOOD</li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>채소</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>국산과일</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>과일·견과·쌀</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>채소</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>수산물·건어물</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>과일·견과</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>정육·계란</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>청과설날선물설날선물설날선물설날선물아아아</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>냉장·냉동·간편식</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>정육·계란</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>라면·면류·즉석밥</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>냉장·냉동·가공식품</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>과자·시리얼·간식</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>라면·면류·즉석밥</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>생수·음료·커피·차</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>과자·시리얼·떡·간식</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>우유·유제품·치즈</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>생수·음료·커피·차</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>조미료·양념·가루·오일</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>우유·유제품·치즈·유아식</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>건강식품</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>조미료·양념·가루·오일</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>베이비·키즈</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>건강식품</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depth_division">LIFE</li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>생활용품</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>냉장·냉동·가공식품</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>뷰티·바디케어</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>라면·면류·즉석밥</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>주방용품</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>과자·시리얼·떡·간식</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>가전·디지털</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>국산과일</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>반려동물·취미</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>국산과일</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                           <li class="depTit">'
+'                             <a href="#"><span>리빙·인테리어</span></a>'
+'                             <div class="depth2">'
+'                               <div class="lb01">'
+'                                 <ul>'
+'                                   <li><a href="#"><span>국산과일</span></a></li>'
+'                                   <li><a href="#"><span>수입과일</span></a></li>'
+'                                   <li><a href="#"><span>냉동·건과일</span></a></li>'
+'                                   <li><a href="#"><span>견과류</span></a></li>'
+'                                   <li><a href="#"><span>갓신선·과일</span></a></li>'
+'                                 </ul>'
+'                               </div>'
+'                             </div>'
+'                           </li>'
+'                         </ul>'
+'                       </div>'
+'                     </div>'
+'                   </div>'
+'                 </ul>'
+'                 <div class="gnbScroll" id="gnbScroll">'
+'                   <div class="list_ctg">'
+'                     <div class="swiper-container">'
+'                       <ul class="list_brd swiper-wrapper">'
+'                         <!-- <li class="fresh swiper-slide"><a href="#"><span></span>KIMS FRESH</a></li> -->'
+'                         <li class="swiper-slide"><a href="#">베스트</a></li>'
+'                         <li class="swiper-slide"><a href="#">자주구매</a></li>'
+'                         <li class="swiper-slide"><a href="#">킴스딜</a></li>'
+'                         <li class="swiper-slide"><a href="#">전문관</a></li>'
+'                         <li class="swiper-slide"><a href="#">기획전</a></li>'
+'                         <li class="swiper-slide"><a href="#">오늘직송</a></li>'
+'                         <li class="swiper-slide"><a href="#">뚝딱레시피</a></li>'
+'                         <li class="swiper-slide"><a href="#">이벤트/쿠폰</a></li>'
+'                       </ul>'
+'                     </div>'
+'                   </div>'
+'                   <div class="cp_controll">'
+'                     <a href="#" class="btn_prev"><span>이전</span></a>'
+'                     <a href="#" class="btn_next"><span>다음</span></a>'
+'                   </div>'
+'                 </div>'
+'               </div>'
+'             </div>'
document.write(headerTag);