var footerIncStr = '';
footerIncStr+='<footer class="footer" id="footer">'
footerIncStr+='	<div class="ft_bn" style="background-color:#ddd2f0">'
footerIncStr+='		<a href="#"><img src="../images/mobile/temp/bn_foot_100.jpg" width="640" height="100" alt="이벤트배너" /></a>'
footerIncStr+='	</div>'
footerIncStr+='	<div class="ft_menu">'
footerIncStr+='		<ul>'
footerIncStr+='			<li><a href="#">로그아웃</a></li>'
footerIncStr+='			<li><a href="#">마이페이지</a></li>'
footerIncStr+='			<li><a href="#">장바구니</a></li>'
footerIncStr+='			<li><a href="#">고객센터</a></li>'
footerIncStr+='		</ul>'
footerIncStr+='	</div>'
footerIncStr+='	<div class="ft_info">'
footerIncStr+='		<p>주식회사 이랜드리테일  서울시 서초구 잠원동 70-2</p>'
footerIncStr+='		<p>대표이사 : 이광일/김연배</p>'
footerIncStr+='		<p>사업자등록번호 : 114-81-01855  <a href="#">사업자정보확인</a></p>'
footerIncStr+='		<p>통신판매업 신고번호 : 서초 제 09998호</p>'
footerIncStr+='		<p>고객센터 : <a href="tel:1899-9500">1899-9500</a></p>'
// footerIncStr+='		<!-- 160926 바로방문 추가 -->'
// footerIncStr+='		<div class="ft_direct">'
// footerIncStr+='			<!-- web에서는 off만 사용 <a href="#"><i class="on">APP방문ON</i></a> -->'
// footerIncStr+='			<a href="#"><i class="off">APP방문OFF</i></a>'
// footerIncStr+='		</div>'
// footerIncStr+='		<!-- //160926 바로방문 추가 -->'
footerIncStr+='	</div>'
footerIncStr+='	<div class="ft_copy">COPYRIGHT 2016@ELAND RETAIL ALL RIGHT RESERVED</div>'
footerIncStr+='	<div class="ft_app">'
footerIncStr+='		<ul>'
footerIncStr+='			<!-- 160901 삭제 <li><a href="#">PC 버전보기</a></li> -->'
footerIncStr+='			<li><a href="#">APP 다운로드</a></li>'
footerIncStr+='		</ul>'
footerIncStr+='	</div>'
footerIncStr+='</footer>'
$('#contents').after(footerIncStr);