var footerTag;
footerTag ='<div class="footer_kms" role="contentinfo">'
+'			<div class="foot">'
+'				<ul class="fnb" role="menu" aria-label="킴스클럽 메뉴">'
+'					<li><a href="#" role="menuitem">로그인</a></li>'
+'					<li><a href="#" role="menuitem">마이페이지</a></li>'
+'					<li><a href="#" role="menuitem">장바구니</a></li>'
+'					<li><a href="#" role="menuitem">공지사항</a></li>'
+'				</ul>'
+'				<dl class="info">'
+'					<dt>(주)이랜드리테일</dt>'
+'					<dd class="addr">'
+'						킴스클럽 고객센터 : <a href="tel:1899-4222">1899-4222</a><br>'
+'						사업자등록번호 : 114-81-01855 <a href="#" target="_blank" title="새창">사업자정보확인</a><br>'
+'						통신판매업 신고번호 : 제2007-서울서초-09998호<br>'
+'						서울시 서초구 잠원동70-2<br>'
+'						대표이사 : 김우섭/석창현<br>'
+'						개인정보 보호책임자 : 이동규<br>'
+'					</dd>'
+'					<dd class="trm">'
+'						<a href="#" target="_blank" title="새창">이용약관</a>'
+'						<a href="#" target="_blank" title="새창">개인정보처리방침</a>'
+'					</dd>'
+'					<dd class="sns">'
+'						<button type="button" class="in" aria-label="인스타그램 이동"></button>'
+'						<button type="button" class="ko" aria-label="카카오스토리 이동"></button>'
+'						<button type="button" class="bg" aria-label="블로그 이동"></button>'
+'					</dd>'
+'					<dd class="cpy">Copyright ⓒ ELANDRETAIL. All Rights Reserved</dd>'
+'					<dd class="cpy">Elandmall 내 판매 상품 중 일부는 개별 판매자의 상품이 포함되어있고, 이 경우 이랜드리테일은 통신판매의 당사자가 아니므로 해당 상품, 거래정보 및 거래에 대하여는 개별 판매자에 책임이 있습니다.</dd>'
+'				</dl>'
+'			</div>'
+'		</div>'
document.write(footerTag);
