# docker build -t ngcp-fo_webroot:${tag} . -f pcweb/DockerFile

FROM nginx:1.15.1-alpine

ENV WWW_BASE /usr/local/nginx

ADD pcweb/nginx.conf /etc/nginx/nginx.conf
ADD . ${WWW_BASE}/fo_webroot

EXPOSE 80

CMD nginx -g 'daemon off;'